// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsnohuirkhjamsqwfjag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbm9odWlya2hqYW1zcXdmamFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTAxNzUsImV4cCI6MjA3MTkyNjE3NX0.bChGxDdvIWPgkTos2dipIkFqUr-yznA-fV8ksA-BkKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});